export const LANGUAGES = [
  {
    language: 'english',
    reader: 'Microsoft Hazel - English (United Kingdom)',
    symbols: [],
  },
  {
    language: 'spanish',
    reader: 'Microsoft Helena - Spanish (Spain)',
    symbols: ['á', 'é', 'í', 'ó', 'ú', 'ü', 'ñ'],
  },
  {
    language: 'polish',
    reader: 'Microsoft Zofia Online (Natural)',
    symbols: ['ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż'],
  },
  {
    language: 'french',
    reader: 'Microsoft Hortense - French (France)',
    symbols: [
      'à',
      'â',
      'æ',
      'ç',
      'é',
      'è',
      'ê',
      'ë',
      'ï',
      'î',
      'ô',
      'ó',
      'œ',
      'ù',
      'û',
      'ü',
      'ÿ',
    ],
  },
];
